import { useQuery } from '@tanstack/react-query'
import { FileDown } from 'lucide-react'
import { api } from '../lib/api'
import { fmtUtc } from '../lib/format'
import { Button, Empty, PageHeader, Spinner, Table } from '../components/Primitives'

export default function Reports() {
  const q = useQuery({ queryKey: ['reports'], queryFn: api.reports })
  return (
    <div className="p-6">
      <PageHeader eyebrow="Evidence packs" title="Reports" description="Each report bundles the radar tile, mask, drift assumptions, ranking breakdown, notes and source hashes." />
      {!q.data ? <Spinner /> : q.data.length === 0 ? <Empty title="No reports yet" /> : (
        <Table>
          <thead><tr><th>Incident</th><th>Generated by</th><th>Generated (UTC)</th><th className="text-right">Pages</th><th></th></tr></thead>
          <tbody>
            {q.data.map((r) => (
              <tr key={r.id}>
                <td className="font-mono">{r.incident_code}</td>
                <td>{r.generated_by}</td>
                <td className="font-mono text-xs">{fmtUtc(r.generated_at)}</td>
                <td className="text-right font-mono tnum">{r.pages}</td>
                <td className="text-right"><Button variant="ghost" disabled title="PDF generation lands in week 7"><FileDown className="size-4" />Download</Button></td>
              </tr>
            ))}
          </tbody>
        </Table>
      )}
    </div>
  )
}
